server:
  port: ${PORT:8080}  # Railway gives PORT, locally 8080

spring:
  application:
    name: user-service

  datasource:
    # Default (local) => MySQL 8
    # Railway => will override via JDBC_DATABASE_URL env var
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/usersdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # auto create/update table
    show-sql: true
    properties:
      hibernate:
        format_sql: true
