spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: your_local_mysql_password

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
