spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    # Direct properties for JPA/Hibernate configuration
    hibernate:
      ddl-auto: 'update' # Controls schema generation (update, create, none, etc.)
    show-sql: true       # Shows all executed SQL statements
    # A map for vendors specific properties
    properties:
      hibernate:
        format_sql: true # Formats the outputted SQL for readability

server:
  port: ${PORT:8080}